version: '3.8'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/cert.key:/etc/nginx/cert.key'
      - './nginx/cert.crt:/etc/nginx/cert.crt'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: 'Asia/Calcutta'
      WEBPASSWORD: changeme
    volumes:
      - './.volumes/pihole/etc-pihole:/etc/pihole'
      - './.volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped


