version: '3.8'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/cert.key:/etc/nginx/cert.key'
      - './nginx/cert.crt:/etc/nginx/cert.crt'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: 'Asia/Calcutta'
      CORS_HOSTS: dns.home
      WEBPASSWORD: 
    volumes:
      - './.volumes/pihole/etc-pihole:/etc/pihole'
      - './.volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './pihole/custom.list:/etc/pihole/custom.list:ro'
      - './pihole/05-pihole-custom-cname.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf:ro'
    restart: unless-stopped

  dashboard:
    container_name: dashboard
    image: pawelmalak/flame
    #image: pawelmalak/flame:multiarch #for Raspberry PI
    volumes:
      - './.volumes/dashboard/app-data:/app/data'
    environment:
      - PASSWORD=changeme

  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped

  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.volumes/portainer/data:/data'
    environment:
      TZ: 'Asia/Calcutta'
    restart: unless-stopped

  vault:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    volumes:
      - './vault/data:/data'
    restart: unless-stopped

  prowlarr:
    image: 'ghcr.io/hotio/prowlarr'
    container_name: prowlarr
    environment:
      TZ: 'Asia/Calcutta'
    volumes:
      - './.volumes/prowlarr/config:/config'


