name: chips-lab

services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '443:443'
      - '8096:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/cert.key:/etc/nginx/cert.key'
      - './nginx/cert.crt:/etc/nginx/cert.crt'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: 'Asia/Calcutta'
      CORS_HOSTS: dns.home
      WEBPASSWORD: 
    volumes:
      - './.volumes/pihole/etc-pihole:/etc/pihole'
      - './.volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './pihole/custom.list:/etc/pihole/custom.list:ro'
      - './pihole/05-pihole-custom-cname.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf:ro'
    restart: unless-stopped

  dashboard:
    image: ghcr.io/benphelps/homepage:latest
    container_name: dashboard
    volumes:
      - './dashboard/config:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped

  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped

  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.volumes/portainer/data:/data'
    environment:
      TZ: 'Asia/Calcutta'
    restart: unless-stopped

  vault:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    volumes:
      - './vault/data:/data'
    restart: unless-stopped

  prowlarr:
    image: 'ghcr.io/hotio/prowlarr'
    container_name: indexer
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '${MEDIA_HOME}/configs/prowlarr:/config'
    restart: unless-stopped

  sonarr:
    image: 'linuxserver/sonarr'
    container_name: series
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '${MEDIA_HOME}/configs/sonarr:/config'
      - '${MEDIA_HOME}/files/sonarr:/data'
      - '${MEDIA_HOME}/files/transmission:/downloads'
    restart: unless-stopped

  radarr:
    image: 'linuxserver/radarr'
    container_name: movies
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '${MEDIA_HOME}/configs/radarr:/config'
      - '${MEDIA_HOME}/files/radarr:/data'
      - '${MEDIA_HOME}/files/transmission:/downloads'
    restart: unless-stopped

  bazarr:
    image: 'ghcr.io/linuxserver/bazarr'
    container_name: subtitles
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '${MEDIA_HOME}/configs/bazarr:/config'
      - '${MEDIA_HOME}/files:/data'
    restart: unless-stopped

  jellyfin:
    image: 'jellyfin/jellyfin'
    container_name: entertainment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    devices:
      - '/dev/dri/renderD128:/dev/dri/renderD128'
      - '/dev/dri/card1:/dev/dri/card1'
    volumes:
      - '${MEDIA_HOME}/configs/jellyfin:/config'
      - '${MEDIA_HOME}/files:/data'
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
      TRANSMISSION_WEB_HOME: #optional
      USER: #optional
      PASS: #optional
      WHITELIST: #optional
      PEERPORT: #optional
      HOST_WHITELIST: #optional
    volumes:
      - '${MEDIA_HOME}/configs/transmission:/config'
      - '${MEDIA_HOME}/files/transmission:/downloads'
    # Ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - './.volumes/influxdb/storage:/var/lib/influxdb'
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: '0'
    volumes:
      - './.volumes/grafana/storage:/var/lib/grafana'
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '${MEDIA_HOME}/configs/calibre:/config'
      - '${MEDIA_HOME}/files/calibre:/books'
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    ports:
      - '8054:8080'
      - '8055:8081'
      - '8156:8181'
    volumes:
      - '${MEDIA_HOME}/files/calibre:/config'
    restart: unless-stopped
