version: '3.8'
name: chips-lab

services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '443:443'
      - '8096:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/cert.key:/etc/nginx/cert.key'
      - './nginx/cert.crt:/etc/nginx/cert.crt'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    environment:
      TZ: 'Asia/Calcutta'
      CORS_HOSTS: dns.home
      WEBPASSWORD: 
    volumes:
      - './.volumes/pihole/etc-pihole:/etc/pihole'
      - './.volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './pihole/custom.list:/etc/pihole/custom.list:ro'
      - './pihole/05-pihole-custom-cname.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf:ro'
    restart: unless-stopped

  dashboard:
    image: ghcr.io/benphelps/homepage:latest
    container_name: dashboard
    environment:
      PUID: 1000 
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - './dashboard/config:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped

  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped

  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.volumes/portainer/data:/data'
    environment:
      TZ: 'Asia/Calcutta'
    restart: unless-stopped

  vault:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    volumes:
      - './vault/data:/data'
    restart: unless-stopped

  prowlarr:
    image: 'ghcr.io/hotio/prowlarr'
    container_name: indexer
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '/home/chips/media/configs/prowlarr:/config'
    restart: unless-stopped

  sonarr:
    image: 'linuxserver/sonarr'
    container_name: series
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '/home/chips/media/configs/sonarr:/config'
      - '/home/chips/media/files/sonarr:/data'
      - '/home/chips/media/files/transmission:/downloads'
    restart: unless-stopped

  radarr:
    image: 'linuxserver/radarr'
    container_name: movies
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '/home/chips/media/configs/radarr:/config'
      - '/home/chips/media/files/radarr:/data'
      - '/home/chips/media/files/transmission:/downloads'
    restart: unless-stopped

  bazarr:
    image: 'ghcr.io/linuxserver/bazarr'
    container_name: subtitles
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '/home/chips/media/configs/bazarr:/config'
      - '/home/chips/media/files:/data'
    restart: unless-stopped

  jellyfin:
    image: 'jellyfin/jellyfin'
    container_name: entertainment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    devices:
      - '/dev/dri/renderD128:/dev/dri/renderD128'
      - '/dev/dri/card0:/dev/dri/card0'
    volumes:
      - '/home/chips/media/configs/jellyfin:/config'
      - '/home/chips/media/files:/data'
    restart: unless-stopped

  ombi:
    image: 'ghcr.io/linuxserver/ombi'
    container_name: request
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
    volumes:
      - '/home/chips/media/configs/ombi:/config'
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Asia/Calcutta'
      TRANSMISSION_WEB_HOME: #optional
      USER: #optional
      PASS: #optional
      WHITELIST: #optional
      PEERPORT: #optional
      HOST_WHITELIST: #optional
    volumes:
      - '/home/chips/media/configs/transmission:/config'
      - '/home/chips/media/files/transmission:/downloads'
    # Ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    restart: unless-stopped
